version: "3.9"

services:
  suricata:
    container_name: suricata
    image: jasonish/suricata:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    command: -i enp6s0
    volumes:
      - ./suricata/var/log/suricata:/var/log/suricata
      - ./suricata/var/lib/suricata:/var/lib/suricata
      - ./suricata/etc/suricata:/etc/suricata

  evebox:
    container_name: evebox
    image: jasonish/evebox:latest
    ports:
      - "5636:5636"
    command: -D /evebox/ --datastore sqlite --input /var/log/suricata/eve.json
    volumes:
      - ./suricata/var/log/suricata:/var/log/suricata:ro
      - ./evebox:/evebox