winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System
  - name: Microsoft-windows-sysmon/operational
  - name: Microsoft-windows-PowerShell/Operational
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

output.elasticsearch:
  hosts: ["http://10.2.96.4:8080/api/v1/ingest/elastic-bulk"]
  password: "abcdabcdabcdabcd"
  compression_level: 5
  bulk_max_size: 200
  worker: 1
